### ISSUE TITLE
Enum cause CANNOT_READ_ALL_DATA

### ISSUE THREAD

**Issue by DualHappiness** [loyd/ch2rs#5]
clickhouse: 23.8.2.7

ch2rs generate code use #[repr(i8)] for enum, but this case CANNOT_READ_ALL_DATA.
by change it to #[repr(u8)] everything is all right. And in [document](https://crates.io/crates/clickhouse) is also u8.
Is this a bug?

**Comment by loyd** [comment]
Hello, can you provide a full example? `#[repr(i8)]` matches `Enum8` in CH, so either you use `Enum16` (and it should be generated as `#[repr(i16)]`) or your schema is broken elsewhere

**Comment by DualHappiness** [comment]
The mvp can't get same result.
